@startuml
'https://plantuml.com/class-diagram

!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml

abstract class Animal {
   roam()
   eat()
}

abstract class Feline
abstract class Canine

abstract class AbstractList {
go()
}
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList
Animal <|- Feline

class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml